export type CategoryType = "command" | "listener";
export type Emitter = "client" | "process";
export type ErrorEmbedType = "INVALID_ARGS" | "MISSING_ARGS" | "USER_PERMISSIONS_MISSING" | "CLIENT_PERMISSIONS_MISSING" | "OWNER_ONLY";
export type ErrorKey = "FILE_NOT_FOUND" | "MODULE_NOT_FOUND" | "ALREADY_LOADED" | "NOT_RELOADABLE" | "INVALID_CLASS_TO_HANDLE" | "ALIAS_CONFLICT" | "COMMAND_UTIL_EXPLICIT" | "UNKNOWN_MATCH_TYPE" | "NOT_INSTANTIABLE" | "NOT_IMPLEMENTED" | "INVALID_TYPE";